<a href="https://colab.research.google.com/github/Viitor22/Linear-Regression-Apple-Predict/blob/main/Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy
!pip install torch==2.5.1 -f https://download.pytorch.org/whl/torch_stable.html
!pip install torchvision==0.20.1 -f https://download.pytorch.org/whl/torch_stable.html
!pip install torchaudio==2.3.1 -f https://download.pytorch.org/whl/torch_stable.html

Looking in links: https://download.pytorch.org/whl/torch_stable.html
Looking in links: https://download.pytorch.org/whl/torch_stable.html
Looking in links: https://download.pytorch.org/whl/torch_stable.html
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 37.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 GB ? eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 234.3/234.3 MB 6.4 MB/s eta 0:00:00
  Attempting uninstall: torch
    Found existing installation: torch 2.5.1+cu121
    Uninstalling torch-2.5.1+cu121:
      Successfully uninstalled torch-2.5.1+cu121
  Attempting uninstall: torchaudio
    Found existing installation: torchaudio 2.5.1+cu121
    Uninstalling torchaudio-2.5.1+cu121:
      Successfully uninstalled torchaudio-2.5.1+cu121
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchvision 0.20.1+cu121 requires 

In [ ]:
import numpy as np
import torch

In [ ]:
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype='float32')

In [ ]:
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype='float32')

In [ ]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [ ]:
w = torch.randn(2,3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[ 0.4607, -1.4922, -0.5483],
        [-0.3522, -0.2914,  0.9041]], requires_grad=True)
tensor([-0.0749,  1.0485], requires_grad=True)


In [ ]:
def model(x):
  return x @ w.t() + b

In [ ]:
preds = model(inputs)
print(preds)

tensor([[ -89.9943,   -5.3088],
        [-124.5509,    1.2184],
        [-191.7453,  -16.1995],
        [ -37.5311,  -13.9548],
        [-149.9139,   12.0607]], grad_fn=<AddBackward0>)


In [ ]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [ ]:
def mse(t1, t2):
  diff = t1 - t2
  return torch.sum(diff * diff) / diff.numel()

In [ ]:
loss = mse(preds, targets)
print(loss)

tensor(27955.8223, grad_fn=<DivBackward0>)


In [ ]:
loss.backward()

In [ ]:
print(w)
print(w.grad)

tensor([[ 0.4607, -1.4922, -0.5483],
        [-0.3522, -0.2914,  0.9041]], requires_grad=True)
tensor([[-15984.1582, -19269.9082, -11472.5732],
        [ -8026.8433,  -9255.2842,  -5529.7891]])


In [ ]:
with torch.no_grad():
  w -= w.grad * 1e-5
  b -= b.grad * 1e-5

In [ ]:
loss = mse(preds, targets)
print(loss)

tensor(27955.8223, grad_fn=<DivBackward0>)


In [ ]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


1 - Generate predictions

2 - Calculate the loss

3 - Compute gradients w.r.t the weights and biases

4 - Adjust the weights by subtracting a small quantity proportional to the gradient

5 - Reset the gradients to zero



In [ ]:
#Generate predictions
preds = model(inputs)
print(preds)

tensor([[ -60.4799,    9.1307],
        [ -85.7034,   20.2076],
        [-145.3614,    6.3942],
        [  -8.6944,    0.2593],
        [-112.3530,   30.3561]], grad_fn=<AddBackward0>)


In [ ]:
# Calculate the loss
loss = mse(preds, targets)
print(loss)

tensor(19403.2734, grad_fn=<DivBackward0>)


In [ ]:
# Compute gradients
loss.backward()
print(w.grad)
print(b.grad)

tensor([[-12932.5332, -15978.4453,  -9444.2031],
        [ -6534.8511,  -7648.5640,  -4539.1426]])
tensor([-158.7184,  -78.7304])


In [ ]:
# Train for 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [ ]:
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(149.4495, grad_fn=<DivBackward0>)


In [ ]:
import torch.nn as nn

In [ ]:
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70],
                   [74, 66, 43],
                   [91, 87, 65],
                   [88, 134, 59],
                   [101, 44, 37],
                   [68, 96, 71],
                   [73, 66, 44],
                   [92, 87, 64],
                   [87, 135, 57],
                   [103, 43, 36],
                   [68, 97, 70]],
                  dtype='float32')

In [ ]:
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119],
                    [57, 69],
                    [80, 102],
                    [118, 132],
                    [21, 38],
                    [104, 118],
                    [57, 69],
                    [82, 100],
                    [118, 134],
                    [20, 38],
                    [102, 120]],
                   dtype='float32')

In [ ]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [ ]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])

In [ ]:
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader

In [ ]:
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [ ]:
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [ ]:
for xb, yb in train_dl:
  print(xb)
  print(yb)
  break

tensor([[ 73.,  67.,  43.],
        [101.,  44.,  37.],
        [ 69.,  96.,  70.],
        [ 68.,  97.,  70.],
        [ 87., 135.,  57.]])
tensor([[ 56.,  70.],
        [ 21.,  38.],
        [103., 119.],
        [102., 120.],
        [118., 134.]])


In [ ]:
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.5363,  0.1515, -0.4989],
        [-0.5683, -0.3605, -0.5668]], requires_grad=True)
Parameter containing:
tensor([ 0.3977, -0.0497], requires_grad=True)


In [ ]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.5363,  0.1515, -0.4989],
         [-0.5683, -0.3605, -0.5668]], requires_grad=True),
 Parameter containing:
 tensor([ 0.3977, -0.0497], requires_grad=True)]

In [ ]:
preds = model(inputs)
preds

tensor([[ -50.0594,  -90.0671],
        [ -67.0095, -119.7715],
        [ -54.9033, -130.6820],
        [ -66.2550,  -94.4951],
        [ -56.9918, -113.5533],
        [ -50.7472,  -90.2749],
        [ -67.6599, -119.9778],
        [ -55.9386, -131.8172],
        [ -65.5672,  -94.2873],
        [ -56.9543, -113.5518],
        [ -50.7097,  -90.2734],
        [ -67.6973, -119.9793],
        [ -54.2530, -130.4758],
        [ -66.2924,  -94.4966],
        [ -56.3039, -113.3455]], grad_fn=<AddmmBackward0>)

In [ ]:
import torch.nn.functional as F

In [ ]:
loss_fn = F.mse_loss

In [ ]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(31212.4004, grad_fn=<MseLossBackward0>)


In [ ]:
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [ ]:
def fit(num_epcohs, model, loss_fn, opt, train_dl):
  for epoch in range(num_epcohs):
    for xb, yb in train_dl:
      pred = model(xb)
      loss = loss_fn(pred, yb)
      loss.backward()
      opt.step()
      opt.zero_grad()

    if (epoch+1) % 10 == 0:
      print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epcohs, loss.item()))

In [ ]:
fit(50, model, loss_fn, opt, train_dl)

Epoch [10/50], Loss: 1.5871
Epoch [20/50], Loss: 1.9347
Epoch [30/50], Loss: 1.7742
Epoch [40/50], Loss: 1.7469
Epoch [50/50], Loss: 1.2193


In [ ]:
preds = model(inputs)
preds

tensor([[ 57.0529,  70.4563],
        [ 81.5470, 100.1177],
        [119.0525, 133.7592],
        [ 21.0256,  38.0177],
        [100.9809, 117.5997],
        [ 55.7939,  69.3686],
        [ 81.3224, 100.1312],
        [119.2981, 134.3169],
        [ 22.2845,  39.1053],
        [102.0153, 118.7009],
        [ 56.8283,  70.4698],
        [ 80.2880,  99.0300],
        [119.2771, 133.7456],
        [ 19.9912,  36.9165],
        [102.2399, 118.6874]], grad_fn=<AddmmBackward0>)

In [ ]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

In [59]:
x = float(input("Digite a temperatura média da região: "))
y = float(input("Digite a umidade média da região: "))
z = float(input("Digite a pressão média da região: "))

Digite a temperatura média da região: 73
Digite a umidade média da região: 67
Digite a pressão média da região: 43


In [60]:
pred = model(torch.tensor([[x, y, z]]))
pred

tensor([[57.0529, 70.4563]], grad_fn=<AddmmBackward0>)

In [61]:
final_pred = pred.detach().numpy()
macas = final_pred[0,0]
laranjas = final_pred[0,1]
print(f"O modelo prevê aproximadamente {round(macas)} toneladas de maçãs e {round(laranjas)} toneladas de laranja")

O modelo prevê aproximadamente 57 toneladas de maçãs e 70 toneladas de laranja
